name: 'TheLogicalNights SpringBoot App Runner '
description: 'TheLogicalNights SpringBoot App Runner '

#inputs:
#    my-input:
#        description: 'Description of my input'
#        required: true
#        default: 'default value'

runs:
    using: 'java'
    main: 'src/main/java/com/example/GitHubActionsReleaseDemo/GitHubActionsReleaseDemoApplication.java'
