name: 'TheLogicalNights SpringBoot App Runner '
description: 'TheLogicalNights SpringBoot App Runner '

#inputs:
#    my-input:
#        description: 'Description of my input'
#        required: true
#        default: 'default value'

runs:
    using: 'docker'
    image: 'Dockerfile'
