name: 'GitHub Actions Release Demo'
description: 'An example GitHub Action for releasing Spring Boot applications.'
branding:
  icon: 'package'
  color: 'blue'

#inputs:
#  version:
#    description: 'The version of the application to release.'
#    required: true
runs:
  using: composite
  main: .github/workflows/run.yaml
