name: 'GitHub Actions Release Demo'
description: 'An example GitHub Action for releasing Spring Boot applications.'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  Username:
    description: 'Username to login'
    required: true
  Password:
    description: "Password to login"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: TheLogicalNights/GitHub-Actions-Release-Demo
        ref: main
        path: ./

#    - name: Debug log
#      run: ls -a
#      shell: bash
      
    - name: Grant execute permissions to mvnw
      run: chmod +x ./mvnw
      shell: bash

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build Spring Boot App
      run: ./mvnw clean package
      shell: bash

    - name: Store Maven dependencies in cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

    - name: Run Spring Boot App
      run: java -jar target/GitHubActionsReleaseDemo-0.0.1-SNAPSHOT.jar
      env:
        USERNAME: ${{ inputs.Username }}
        PASSWORD: ${{ inputs.Password }}
      shell: bash
      