services:
  myapp:
    image: sadhav512/github-actions:latest
    volumes:
      - /outputs:/app/outputs
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    ports:
      - "8080:8080"
