version: '1.0.1'
services:
  myapp:
    image: your-docker-hub-username/my-spring-boot-app:${{ github.sha }}
    environment:
      - USERNAME=${{ inputs.USERNAME }}
      - PASSWORD=${{ inputs.PASSWORD }}
    ports:
      - "8080:8080"
