version: '1.0.1'
services:
  myapp:
    image: sadhav512/github-actions:latest
    environment:
      - USERNAME=${{ inputs.USERNAME }}
      - PASSWORD=${{ inputs.PASSWORD }}
    ports:
      - "8080:8080"
